//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clinical_Reporting.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Biochemistry
    {
        public long SerialNo { get; set; }
        public long PatientID { get; set; }
        public Nullable<System.DateTime> TDate { get; set; }
        public string Blood_Sugar_Fasting { get; set; }
        public string Blood_Sugar_Fasting_Unit { get; set; }
        public string Blood_Sugar_Fasting_Nor { get; set; }
        public string Blood_Sugar_2HPP { get; set; }
        public string Blood_Sugar_2HPP_Unit { get; set; }
        public string Blood_Sugar_2HPP_Nor { get; set; }
        public string Blood_Sugar_Random { get; set; }
        public string Blood_Sugar_Random_Unit { get; set; }
        public string Blood_Sugar_Random_Nor { get; set; }
        public string Blood_Urea { get; set; }
        public string Blood_Urea_Unit { get; set; }
        public string Blood_Urea_Nor { get; set; }
        public string BUN { get; set; }
        public string BUN_Unit { get; set; }
        public string BUN_Nor { get; set; }
        public string S_Creatinine { get; set; }
        public string S_Creatinine_Unit { get; set; }
        public string S_Creatinine_Nor { get; set; }
        public string S_Uric_Acid { get; set; }
        public string S_Uric_Acid_Unit { get; set; }
        public string S_Uric_Acid_Nor { get; set; }
        public string S_Cholestrol { get; set; }
        public string S_Cholestrol_Unit { get; set; }
        public string S_Cholestrol_Nor { get; set; }
        public string S_Triglycerides { get; set; }
        public string S_Triglycerides_Unit { get; set; }
        public string S_Triglycerides_Nor { get; set; }
        public string HDL_Cholestrol { get; set; }
        public string HDL_Cholestrol_Unit { get; set; }
        public string HDL_Cholestrol_Nor { get; set; }
        public string LDL_Cholestrol { get; set; }
        public string LDL_Cholestrol_Unit { get; set; }
        public string LDL_Cholestrol_Nor { get; set; }
        public string SGOT_AST { get; set; }
        public string SGOT_AST_Unit { get; set; }
        public string SGOT_Nor { get; set; }
        public string LDH { get; set; }
        public string LDH_Unit { get; set; }
        public string LDH_Nor { get; set; }
        public string CPK { get; set; }
        public string CPK_Unit { get; set; }
        public string CPK_Nor { get; set; }
        public string CKMB { get; set; }
        public string CKMB_Unit { get; set; }
        public string CKMB_Nor { get; set; }
        public string S_Bilirubin_T { get; set; }
        public string S_Bilirubin_T_Unit { get; set; }
        public string S_Bilirubin_T_Nor { get; set; }
        public string S_Bilirubin_D { get; set; }
        public string S_Bilirubin_D_Unit { get; set; }
        public string S_Bilirubin_D_Nor { get; set; }
        public string S_Bilirubin_Ind { get; set; }
        public string S_Bilirubin_Ind_Unit { get; set; }
        public string S_Bilirubin_Ind_Nor { get; set; }
        public string S_Alk_Phosphatase { get; set; }
        public string S_Alk_Phosphatase_Unit { get; set; }
        public string S_Alk_Phosphatase_Nor { get; set; }
        public string SGPT_ALT { get; set; }
        public string SGPT_ALT_Unit { get; set; }
        public string SGPT_ALT_Nor { get; set; }
        public string S_Sodium { get; set; }
        public string S_Sodium_Unit { get; set; }
        public string S_Sodium_Nor { get; set; }
        public string S_Potassium { get; set; }
        public string S_Potassium_Unit { get; set; }
        public string S_Potassium_Nor { get; set; }
        public string S_Chloride { get; set; }
        public string S_Chloride_Unit { get; set; }
        public string S_Chloride_Nor { get; set; }
        public string S_Calcium { get; set; }
        public string S_Calcium_Unit { get; set; }
        public string S_Calcium_Nor { get; set; }
        public string S_Protein { get; set; }
        public string S_Protein_Unit { get; set; }
        public string S_Protein_Nor { get; set; }
        public string S_Albumin { get; set; }
        public string S_Albumin_Unit { get; set; }
        public string S_Albumin_Nor { get; set; }
        public string AG_Ratio { get; set; }
        public string AG_Ratio_Unit { get; set; }
        public string AG_Ratio_Nor { get; set; }
        public Nullable<int> Fee { get; set; }
    
        public virtual Patient Patient { get; set; }
    }
}
