//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clinical_Reporting.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UrineExamination
    {
        public long SerialNo { get; set; }
        public long PatientID { get; set; }
        public Nullable<System.DateTime> TDate { get; set; }
        public string Colour { get; set; }
        public string Reaction { get; set; }
        public string Specific_Gravity { get; set; }
        public string Albumin { get; set; }
        public string Sugar { get; set; }
        public string Ketone { get; set; }
        public string Blood { get; set; }
        public string Bilirubin { get; set; }
        public string Urobil_Nogen { get; set; }
        public string Pus_Cells { get; set; }
        public string RBC { get; set; }
        public string EPi_Cells { get; set; }
        public string Cast { get; set; }
        public string Crystals { get; set; }
        public string Cal_Oxalate { get; set; }
        public string Uric_Acid { get; set; }
        public string Amorphous { get; set; }
        public string Others { get; set; }
        public Nullable<int> Fee { get; set; }
    
        public virtual Patient Patient { get; set; }
    }
}
