//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel;
using System;
using System.Collections.Generic;
using Dapper;
using Dapper.Contrib.Extensions;
using AdmissionAndResult.Model;

namespace AdmissionAndResult.Model.Wrapper
{
   
 
    class CourseW : IDataErrorInfo
    {

        public long Course_Id { get; set; }
        public string Course_Name { get; set; }
        public long Student_Id { get; set; }
        public CourseW (Course course)
        {
            this.Course_Id=course.Course_Id  ;
            this.Course_Name = course.Course_Name;
            this.Student_Id=course.Student_Id  ;
            
        }
         public CourseW()
         {
             
         }
   


        public string Error
        {
            get { return string.Empty; }
        }

        public string this[string columnName]
        {
            get
            {
                switch (columnName)
                {
                    case "Course_Name":
                        if (string.IsNullOrEmpty(Course_Id.ToString()))
                            return "Admin Name is required";
                        break;
                    case "Student_Id":
                        if (string.IsNullOrEmpty(Course_Name))
                            return "Password is Required";
                        break;
                }
                return "";
            }
        }
    }
}
