//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel;
using System.Drawing;

namespace AdmissionAndResult.Model.Wrapper
{
    using System;
    using System.Collections.Generic;
  
    using System.ComponentModel.DataAnnotations;
    using Dapper.Contrib.Extensions;
    using AdmissionAndResult;
    using Dapper;
    using AdmissionAndResult.Services;
    using AdmissionAndResult.Model;

  
     class StudentW : ValidateModelCommon
    {
    public StudentW (Student student)
        {
            this.Student_Id = student.Student_Id;
            this.Student_Name = student.Student_Name;
            this.Student_Email = student.Student_Email;
            this.Father_Name = student.Father_Name;
            this.Fathers_Number = student.Fathers_Number;
            this.Father_Monthly_Income = student.Father_Monthly_Income;
            this.Father_Occupation = student.Father_Occupation;
            this.Postal_Address = student.Postal_Address;
            this.Permanent_Address = student.Permanent_Address;
            this.Date_Of_Birth = student.Date_Of_Birth;
            this.NIC_No = student.NIC_No;
            this.Blood_Group = student.Blood_Group;
            this.Phone_Number = student.Phone_Number;
            this.Residental_Phone_Number = student.Residental_Phone_Number;
            this.Date = student.Date;
            this.Verified_Bachelor_CGPA = student.Verified_Bachelor_CGPA;
            this.Verified_FSC_Marks = student.Verified_FSC_Marks;
            this.Verified_GAT_Marks = student.Verified_GAT_Marks;
            this.Verified_Matric_Marks = student.Verified_Matric_Marks;
            this.Verified_NTS_Marks = student.Verified_NTS_Marks;
            //this.Image = student.Image;

        }
    public StudentW()
    {

    }

        public long Student_Id { get;set; }
        [Required]
        public string Student_Name { get;set; }
        public string Student_Email { get; set; }
        public string Father_Name { get; set; }
        public string Fathers_Number { get; set; }
        public string Father_Monthly_Income { get; set; }
        public string Father_Occupation { get; set; }
        public string Postal_Address { get; set; }
        public string Permanent_Address { get; set; }
        public string Date_Of_Birth { get; set; }
        public string NIC_No{ get; set; }
        public string Blood_Group { get; set; }
        public string Phone_Number { get; set; }
        public string Residental_Phone_Number { get; set; }
        public string Date { get; set; }
        public long Verified_Matric_Marks { get; set; }
        public long Verified_FSC_Marks { get; set; }
        public long Verified_NTS_Marks { get; set; }
        public long Verified_GAT_Marks { get; set; }
        public long Verified_Bachelor_CGPA { get; set; }
        //public Image Image { get; set; }

        //public string Error
        //{
        //    get { return string.Empty; }
        //}

        //public string this[string columnName]
        //{
        //    get
        //    {
        //        switch (columnName)
        //        {
        //            case "Student_Name":
        //                if (string.IsNullOrEmpty(Student_Name))
        //                    return "Sthdent Name is required";
        //                break;
        //            case "Student_Email":
        //                if (string.IsNullOrEmpty(Student_Email))
        //                    return "Student Email is Required";
        //                break;
        //            case "Father_Name":
        //                if (string.IsNullOrEmpty(Father_Name))
        //                    return "Father Name is required";
        //                break;
        //            case "Father_Monthly_Income":
        //                if (string.IsNullOrEmpty(Father_Monthly_Income))
        //                    return "Father Monthly Income is Required";
        //                break;

        //            case "Father_Occupation":
        //                if (string.IsNullOrEmpty(Father_Occupation))
        //                    return "Father Occupation is required";
        //                break;
        //            case "Postal_Address":
        //                if (string.IsNullOrEmpty(Postal_Address))
        //                    return "Postal address is required";
        //                break;
        //            case "Permanent_Address":
        //                if (string.IsNullOrEmpty(Permanent_Address))
        //                    return "Permanent Address is required";
        //                break;
        //            case "Date_Of_Birth":
        //                if (string.IsNullOrEmpty(Date_Of_Birth))
        //                    return "Date of Birth is required";
        //                break;
        //            case "NIC_No":
        //                if (string.IsNullOrEmpty(NIC_No))
        //                    return "N.I.C No. is required";
        //                break;
        //            case "Blood_Group_":
        //                if (string.IsNullOrEmpty(Blood_Group))
        //                    return "Blood Group is required";
        //                break;
        //            case "Phone_Number":
        //                if (string.IsNullOrEmpty(Phone_Number))
        //                    return "Board Name is required";
        //                break;
        //            case "Residental_Phone_Number":
        //                if (string.IsNullOrEmpty(Residental_Phone_Number))
        //                    return "Residental Phone Number is required";
        //                break;
        //            case "Date":
        //                if (string.IsNullOrEmpty(Date))
        //                    return "Date is required";
        //                break;

        //        }

        //        return "";
        //    }
        //}
    }
}
