//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clinical_Reporting.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BloodGroup
    {
        public long SerialNo { get; set; }
        public long PatientID { get; set; }
        public Nullable<System.DateTime> TDate { get; set; }
        public string Patient_Blood_Group { get; set; }
        public string Donar_Name { get; set; }
        public string Donar_Blood_Group { get; set; }
        public string HbsAg { get; set; }
        public string AntiHCV { get; set; }
        public Nullable<int> Fee { get; set; }
    
        public virtual Patient Patient { get; set; }
    }
}
