//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clinical_Reporting.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ELISA_TB
    {
        public long SerialNo { get; set; }
        public long PatientID { get; set; }
        public Nullable<System.DateTime> TDate { get; set; }
        public Nullable<double> Patient_Value { get; set; }
        public Nullable<double> Cut_Off_Value { get; set; }
        public Nullable<int> Fee { get; set; }
    
        public virtual Patient Patient { get; set; }
    }
}
