//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clinical_Reporting.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Haematology
    {
        public long SerialNo { get; set; }
        public long PatientID { get; set; }
        public Nullable<System.DateTime> TDate { get; set; }
        public string HB { get; set; }
        public string HB_Unit { get; set; }
        public string HB_Nor { get; set; }
        public string TLC { get; set; }
        public string TLC_Unit { get; set; }
        public string TLC_Nor { get; set; }
        public string ESR { get; set; }
        public string ESR_Unit { get; set; }
        public string ESR_Nor { get; set; }
        public string BT { get; set; }
        public string BT_Unit { get; set; }
        public string BT_Nor { get; set; }
        public string CT { get; set; }
        public string CT_Unit { get; set; }
        public string CT_Nor { get; set; }
        public string Platelets_Count { get; set; }
        public string Platelets_Count_Unit { get; set; }
        public string Platelets_Count_Nor { get; set; }
        public string PT { get; set; }
        public string PT_Unit { get; set; }
        public string PT_Nor { get; set; }
        public string DLC { get; set; }
        public string DLC_Unit { get; set; }
        public string DLC_Nor { get; set; }
        public string Polymorphs { get; set; }
        public string Polymorphs_Unit { get; set; }
        public string Polymorphs_Nor { get; set; }
        public string Lymphocytes { get; set; }
        public string Lymphocytes_Unit { get; set; }
        public string Lymphocytes_Nor { get; set; }
        public string Monocyte { get; set; }
        public string Monocyte_Unit { get; set; }
        public string Monocyte_Nor { get; set; }
        public string Eosinophil { get; set; }
        public string Eosinophil_Unit { get; set; }
        public string Eosinophil_Nor { get; set; }
        public string Basophil { get; set; }
        public string Basophil_Unit { get; set; }
        public string Basophil_Nor { get; set; }
        public string Malaria_Parasites { get; set; }
        public string Malaria_Parasites_Unit { get; set; }
        public string Malaria_Parasites_Nor { get; set; }
        public string Blood_Group { get; set; }
        public string Blood_Group_Unit { get; set; }
        public string Blood_Group_Nor { get; set; }
        public string RH_Factor { get; set; }
        public string RH_Factor_Unit { get; set; }
        public string RH_Factor_Nor { get; set; }
        public string Total_R_B_C { get; set; }
        public string Total_R_B_C_Unit { get; set; }
        public string Total_R_B_C_Nor { get; set; }
        public string P_V_C_Haematorcrit { get; set; }
        public string P_V_C_Haematorcrit_Unit { get; set; }
        public string P_V_C_Haematorcrit_Nor { get; set; }
        public string M_C_V { get; set; }
        public string M_C_V_Unit { get; set; }
        public string M_C_V_Nor { get; set; }
        public string M_C_H { get; set; }
        public string M_C_H_Unit { get; set; }
        public string M_C_H_Nor { get; set; }
        public string M_C_H_C { get; set; }
        public string M_C_H_C_Unit { get; set; }
        public string M_C_H_C_Nor { get; set; }
        public Nullable<int> Fee { get; set; }
    
        public virtual Patient Patient { get; set; }
    }
}
