//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clinical_Reporting.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DatabaseContainer : DbContext
    {
        public DatabaseContainer()
            : base("name=DatabaseContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Biochemistry> Biochemistries { get; set; }
        public virtual DbSet<BloodGroup> BloodGroups { get; set; }
        public virtual DbSet<Doctor> Doctors { get; set; }
        public virtual DbSet<ELISA_HBSAG> ELISA_HBSAG { get; set; }
        public virtual DbSet<ELISA_HCV> ELISA_HCV { get; set; }
        public virtual DbSet<ELISA_TB> ELISA_TB { get; set; }
        public virtual DbSet<Haematology> Haematologies { get; set; }
        public virtual DbSet<Patient> Patients { get; set; }
        public virtual DbSet<SemenAnalysi> SemenAnalysis { get; set; }
        public virtual DbSet<Serology> Serologies { get; set; }
        public virtual DbSet<UrineExamination> UrineExaminations { get; set; }
    }
}
