//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clinical_Reporting.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Serology
    {
        public long SerialNo { get; set; }
        public long PatientID { get; set; }
        public Nullable<System.DateTime> TDate { get; set; }
        public string Widal_Test { get; set; }
        public string S_Typhi_TO { get; set; }
        public string S_Typhi_TH { get; set; }
        public string Para_Thyphi_Ah { get; set; }
        public string Para_Thyphi_Bh { get; set; }
        public string HBS_Ag { get; set; }
        public string ASO_Titre { get; set; }
        public string Pregnancy_Test { get; set; }
        public string RA_Factor { get; set; }
        public string Anti_Hcv { get; set; }
        public string Mantoex { get; set; }
        public string Kahns_VDRL { get; set; }
        public string TB_Plus { get; set; }
        public string HIV { get; set; }
        public Nullable<int> Fee { get; set; }
    
        public virtual Patient Patient { get; set; }
    }
}
