//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel;

namespace Model
{
    using System;
    using System.Collections.Generic;
    using Dapper;
    using Dapper.Contrib.Extensions;
    [Table("Course")]
    public partial class Course 
    {
        
   
        [Key]
        public long Course_Id { get; set; }
        public string Course_Name { get; set; }
        public long Student_Id { get; set; }
        public virtual Student Student { get; set; }

        //public string Error
        //{
        //    get { throw new NotImplementedException(); }
        //}

        //public string this[string columnName]
        //{
        //    get
        //    {
        //        switch (columnName)
        //        {
        //            case "Course_Name":
        //                if (string.IsNullOrEmpty(Course_Id.ToString()))
        //                    return "Admin Name is required";
        //                break;
        //            case "Student_Id":
        //                if (string.IsNullOrEmpty(Course_Name))
        //                    return "Password is Required";
        //                break;
        //        }
        //        return "";
        //    }
        //}
    }
}
