//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel;

namespace Model
{
    using System;
    using System.Collections.Generic;
    using Dapper;
    using Dapper.Contrib.Extensions;
    [Table("Qualification")]
    public partial class Qualification : IDataErrorInfo
    {
        [Key]
        public long Qualification_Id { get; set; }
        public long NTS_Obt_Marks { get; set; }
        public long NTS_Max_Marks { get; set; }
        public long FSC_Obt_Marks { get; set; }
        public long FSC_Max_Marks { get; set; }


        public long Matric_Obt_Marks { get; set; }
        public long Matric_Max_Marks { get; set; }

        public long GAT_Obt_Marks { get; set; }
        public long GAT_Max_Marks { get; set; }

        public string Matric_Year { get; set; }

        public string FSC_Year { get; set; }
        public string NTS_Year { get; set; }
        public string BS_Year { get; set; }
        public string MS_Year { get; set; }
        public string GAT_Year { get; set; }







        public string MS_Institute_Name { get; set; }
        public string BS_Institute_Name { get; set; }
        public string FSC_Institute_Name { get; set; }
        public string Matric_Institute_Name { get; set; }




        public string MS_Roll_No { get; set; }
        public string BS_Roll_No { get; set; }
        public string Fsc_Roll_No { get; set; }
        public string Matric_Roll_No { get; set; }
        public string NTS_Roll_No { get; set; }
        public string GAT_Roll_No { get; set; }

        public string BS_Degree { get; set; }
        public string MS_Degree { get; set; }




        public string Board_Name { get; set; }
        //public long GAT_Marks { get; set; }
        public long Batchlor_Obt_CGPA { get; set; }
        public long Batchlor_Max_CGPA { get; set; }

        public long MSC_Obt_CGPA { get; set; }
        public long MSC_Max_CGPA { get; set; }

        public long Verified_NTS_Marks { get; set; }
        public long Verified_FSC_Marks { get; set; }
        public long Verified_Matric_Marks { get; set; }
        public long Verified_GAT_Marks { get; set; }
        public long Verified_MSC_CGPA { get; set; }
        public long Verified_BS_CGPA { get; set; }
    
        public virtual Student Student { get; set; }

        public string Error
        {
            get { throw new NotImplementedException(); }
        }

        public string this[string columnName]
        {
            get
            {
                switch (columnName)
                {
                    case "Nts_Obt_Marks":
                        if (string.IsNullOrEmpty(NTS_Obt_Marks.ToString()))
                            return "Nts marks is required";
                        break;
                    case "FSC_Obt_Marks":
                        if (string.IsNullOrEmpty(FSC_Obt_Marks.ToString()))
                            return "FSC marks is Required";
                        break;
                    case "Matric_Year":
                        if (string.IsNullOrEmpty(Matric_Year))
                            return "Year is required";
                        break;
                    case "Matric_Obt_Mark":
                        if (string.IsNullOrEmpty(Matric_Obt_Marks.ToString()))
                            return "Matric marks is Required";
                        break;
                    case "Matric_Institute_Name":
                        if (string.IsNullOrEmpty(Matric_Institute_Name))
                            return "Institute Name is required";
                        break;
                    case "Matric_Roll_No":
                        if (string.IsNullOrEmpty(Matric_Roll_No))
                            return "Roll No. is required";
                        break;
                    case "Board_Name":
                        if (string.IsNullOrEmpty(Board_Name))
                            return "Board Name is required";
                        break;
                    case "Gat_Obt_Mark":
                        if (string.IsNullOrEmpty(GAT_Obt_Marks.ToString()))
                            return "GAT marks is Required";
                        break;
                    case "Batchlor_Obt_CGPA":
                        if (string.IsNullOrEmpty(Batchlor_Obt_CGPA.ToString()))
                            return "Batchelor CGPA is Required";
                        break;
                    case "MSC_Obt_CGPA":
                        if (string.IsNullOrEmpty(MSC_Obt_CGPA.ToString()))
                            return "MSC CGPA is Required";
                        break;
                        
                }
                return "";
            }
        }
    }
}
