//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    using Dapper;

    [Table("Verifying_Agent")]
    public partial class Verifying_Agent
    {
        [Key]
        public long Verifying_Agent_Id { get; set; }
        public string Verifying_Agent_Name { get; set; }
        public long Verified_Marks { get; set; }
        public long Verified_CGPA { get; set; }
        public string Degree_Verification { get; set; }
        public long Admin_Id { get; set; }
        public string Degree { get; set; }
        public long Eligible { get; set; }
        public string Send_Date { get; set; }
        public string Recive_Date { get; set; }
        public long Student_Id { get; set; }
        public virtual Admin Admin { get; set; }
        public virtual Student Student { get; set; }
    }
}
