//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    using Dapper;
    [Table("Qualification")]
    public partial class Qualification
    {
        [Key]
        public long Qualification_Id { get; set; }
        public long NTS_Marks { get; set; }
        public long FSC_Marks { get; set; }
        public long Matric_Mark { get; set; }
        public string Year { get; set; }
        public string Institute_Name { get; set; }
        public string Roll_No { get; set; }
        public string Board_Name { get; set; }
        public long GAT_Marks { get; set; }
        public long Batchlor_CGPA { get; set; }
        public long MSC_CGPA { get; set; }
    
        public virtual Student Student { get; set; }
    }
}
