//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    using Dapper;
    [Table("Student")]
    public partial class Student
    {
    
        [Key]
        public long Student_Id { get; set; }
        public string Student_Name { get; set; }
        public string Student_Email { get; set; }
        public string Father_Name { get; set; }
        public string Father_Monthly_Income { get; set; }
        public string Father_Occupation { get; set; }
        public string Postal_Address { get; set; }
        public string Permanent_Address { get; set; }
        public string Date_Of_Birth { get; set; }
        public string NIC_No_ { get; set; }
        public string Blood_Group { get; set; }
        public string Phone_Number { get; set; }
        public string Residental_Phone_Number { get; set; }
        public string Date { get; set; }
    
     
        public virtual IEnumerable<Course> Courses { get; set; }
        public virtual IEnumerable<Department> Departments { get; set; }
        public virtual Qualification Qualification { get; set; }
        public virtual IEnumerable<Selected_Student> Selected_Student { get; set; }
        public virtual IEnumerable<Verifying_Agent> Verifying_Agent { get; set; }
    }
}
