//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Text;

namespace SystemDB.Data.Entities
{



    public partial class Admin
    {
        public Admin()
        {
            VerifyingAgents = new List<VerifyingAgent>();
        }

        public long AdminId { get; set; }
        public string AdminName { get; set; }
        public string Password { get; set; }
        public string HireDate { get; set; }
        public string ChangeDate { get; set; }

        public virtual ICollection<VerifyingAgent> VerifyingAgents { get; set; }
    }
}