//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel;
using System;
using System.Collections.Generic;
using Dapper;
using Dapper.Contrib.Extensions;
using AdmissionAndResult.Model;

namespace AdmissionAndResult.Model.Wrapper
{
    
    class DepartmentW : IDataErrorInfo
    {

        public long Department_ID { get; set; }
        public long Student_Id { get; set; }
        public string Department_Name { get; set; }
        public long Student_Strength { get; set; }
        public string HOD_Name { get; set; }
        public string Location { get; set; }

        public DepartmentW(Department department)
        {
           
            this.Department_ID=department.Department_ID  ;
            this.Department_Name=department.Department_Name ;
            this.HOD_Name=department.HOD_Name  ;
            this.Location=department.Location  ;
            
            this.Student_Id= department.Student_Id  ;
            this.Student_Strength=department.Student_Strength  ;
        }
        public DepartmentW()
        {

        }
      
      

        public string Error
        {
            get { throw new NotImplementedException(); }
        }

        public string this[string columnName]
        {
            get
            {
                switch (columnName)
                {
                    case "Student_Id":
                        if (string.IsNullOrEmpty(Department_ID.ToString()))
                            return "Student ID is required";
                        break;
                    case "Department_Name":
                        if (string.IsNullOrEmpty(Department_Name))
                            return "Department Name is Required";
                        break;
                }
                return "";
            }
        }
    }
}
